{% set name = "cairo" %}
{% set version = "1.18.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://cairographics.org/releases/{{ name }}-{{ version }}.tar.xz
  sha256: 445ed8208a6e4823de1226a74ca319d3600e83f6369f99b14265006599c32ccb
  patches:
    - patches/unvendor.patch  

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('cairo') }}
  missing_dso_whitelist:         # [linux and x86_64]
    - '**/libc.so.6'             # [linux and x86_64]
    - '**/libpthread.so.0'       # [linux and x86_64]
    - '**/libdl.so.2'            # [linux and x86_64]
    - '**/librt.so.1'            # [linux and x86_64]
    - '**/libm.so.6'             # [linux and x86_64]

requirements:
  build:
    - pkg-config
    - ninja-base
    - meson
    - xz  # [unix]
    - m2w64-xz  # [win]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - fontconfig {{ fontconfig }}
    - freetype {{ freetype }}
    - glib {{ glib }}
    - libpng {{ libpng }}
    - pixman {{ pixman }}
    - libxcb {{ libxcb }}                    # [linux]
    - xorg-libx11 {{ xorg_libx11 }}          # [linux]
    - xorg-libxext {{ xorg_libxext }}        # [linux]
    - xorg-libxrender {{ xorg_libxrender }}  # [linux]
    - zlib {{ zlib }}
  run:
    - fontconfig
    - freetype
    - libpng
    - libxcb  # [linux]
    - pixman
    - zlib

test:
  requires:
    - pkg-config
  commands:
    # Check commands.
    - cairo-trace --help  # [unix]

    # Verify libraries.
    {% set cairo_libs = [
            "libcairo",
            "libcairo-gobject",
            "libcairo-script-interpreter",
    ] %}
    {% for each_cairo_lib in cairo_libs %}
    - test -f $PREFIX/lib/{{ each_cairo_lib }}${SHLIB_EXT}  # [unix]
    {% endfor %}
    - if not exist %LIBRARY_BIN%\\cairo*.dll exit 1          # [win]
    - if not exist %LIBRARY_LIB%\\cairo.lib exit 1          # [win]
    - if not exist %LIBRARY_BIN%\\cairo-gobject*.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\cairo-gobject.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\cairo-script-interpreter*.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\cairo-script-interpreter.lib exit 1  # [win]

    # Check pkg-config files.
    - test -f $PREFIX/lib/pkgconfig/cairo-quartz.pc             # [osx]
    - test -f $PREFIX/lib/pkgconfig/cairo-xlib.pc               # [linux]   
    - if not exist %LIBRARY_LIB%\\pkgconfig\\cairo.pc exit 1    # [win]  

    # check include files
    - test -f $PREFIX/include/cairo/cairo.h               # [unix]    
    - if not exist %LIBRARY_INC%\\cairo\\cairo.h exit 1   # [win]        

    # check that cairo was built with fontconfig support
    - grep -q "CAIRO_HAS_FC_FONT 1" $PREFIX/include/cairo/cairo-features.h  # [unix]
    
    # verify pkg-config functionality
    - export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig        # [unix]
    - set "PKG_CONFIG_PATH=%LIBRARY_LIB%\\pkgconfig"      # [win]
    - pkg-config --cflags cairo
    - pkg-config --cflags cairo-fc                         # [unix]
    - pkg-config --cflags cairo-gobject

about:
  home: https://cairographics.org/
  dev_url: https://gitlab.freedesktop.org/cairo/cairo
  doc_url: https://cairographics.org/documentation/
  license: LGPL-2.1-or-later or MPL-1.1
  license_file: 
    - COPYING
    - COPYING-LGPL-2.1
    - COPYING-MPL-1.1
  license_family: LGPL
  summary: 'Cairo is a 2D graphics library with support for multiple output devices.'
  description: |
    Cairo is a 2D graphics library with support for multiple output devices.
    It is designed to produce consistent output on all output media while
    taking advantage of display hardware acceleration when available.

extra:
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - ocefpaf
    - pkgw
  skip-lints:
    - patch_unnecessary