{% set version = "1.14.6" %}

package:
  name: cairo
  version: {{ version }}

source:
  fn: cairo-{{ version }}.tar.xz
  url: http://cairographics.org/releases/cairo-{{ version }}.tar.xz
  sha256: 613cb38447b76a93ff7235e17acd55a78b52ea84a9df128c3f2257f8eaa7b252

build:
  number: 0
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]

requirements:
  build:
    - python                  # [win]
    - posix  # [win]
    - m2w64-xz  # [win]
    - pkg-config              # [unix]
    - libtool                 # [unix]
    - xz 5.2.*                # [unix]
    - freetype 2.6.*           # [unix]
    - fontconfig 2.11.*       # [unix]
    - pixman
    - libpng >=1.6.23,<1.7
    - zlib 1.2.*
    - icu 56.*
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]
  run:
    - freetype 2.6.*           # [unix]
    - fontconfig 2.11.*       # [unix]
    - libpng >=1.6.23,<1.7
    - pixman
    - zlib 1.2.*
    - icu 56.*
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]

test:
  commands:
    # Check commands.
    - cairo-trace --help  # [not win]

    # Verify libraries.
    {% set cairo_libs = [
            "libcairo",
            "libcairo-script-interpreter",
    ] %}
    {% for each_cairo_lib in cairo_libs %}
    - test -f $PREFIX/lib/{{ each_cairo_lib }}.a      # [unix]
    - test -f $PREFIX/lib/{{ each_cairo_lib }}.dylib  # [osx]
    - test -f $PREFIX/lib/{{ each_cairo_lib }}.so     # [linux]
    {% endfor %}
    #- conda inspect linkages -p $PREFIX cairo  # [not win]
    #- conda inspect objects -p $PREFIX cairo  # [osx]

about:
  home: http://cairographics.org/
  license: LGPL 2.1 or MPL 1.1
  summary: 'Cairo is a 2D graphics library with support for multiple output devices.'

extra:
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - ocefpaf
