{% set version = "1.14.10" %}

package:
  name: cairo
  version: {{ version }}

source:
  fn: cairo-{{ version }}.tar.xz
  url: http://cairographics.org/releases/cairo-{{ version }}.tar.xz
  sha1: 28c59d85d6b790c21b8b59ece73a6a1dda28d69a

build:
  number: 4
  skip: True  # [win and py>35]
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]

requirements:
  build:
    - {{ compiler('c') }}
    - python  # [win]
    - posix  # [win]
    - m2w64-xz  # [win]
    - pkg-config  # [not win]
    - libtool  # [not win]
  host:
    - fontconfig  # [not win]
    - freetype  # [not win]
    - glib  # [not win]
    - icu
    - libpng
    - xz  # [not win]
    - zlib
    - pixman 0.34.*
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]
  run:
    - pixman 0.34.*
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]

test:
  commands:
    # Check commands.
    - cairo-trace --help  # [not win]

    # Verify libraries.
    {% set cairo_libs = [
            "libcairo",
            "libcairo-gobject",
            "libcairo-script-interpreter",
    ] %}
    {% for each_cairo_lib in cairo_libs %}
    - test -f $PREFIX/lib/{{ each_cairo_lib }}.a      # [not win]
    - test -f $PREFIX/lib/{{ each_cairo_lib }}.dylib  # [osx]
    - test -f $PREFIX/lib/{{ each_cairo_lib }}.so     # [linux]
    {% endfor %}
    - conda inspect linkages -p $PREFIX cairo  # [not win]
    - conda inspect objects -p $PREFIX cairo  # [osx]

about:
  home: http://cairographics.org/
  license: LGPL 2.1 or MPL 1.1
  summary: 'Cairo is a 2D graphics library with support for multiple output devices.'

extra:
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - ocefpaf
    - pkgw
