travis:
  secure:
    BINSTAR_TOKEN: jpZBE1sImOG7Wt4GSyVORrWe/Lde3lgOzE4vJwI3Fle0YxVJRyuJr2rzSMZHxzAr9H1q3bPmS+qOrfzyqbwEnZYq3DJhjtyxOGLJFfYx3LBxdEHDq1/O7eK5i3AKB8XPKe/6zWIQXa9tZOOw3TTUujdGKQD/vMNTSglvx9oBYt6bJDy0uMtqNb5sR4rEthuN35g6MArXLDUSkwr/NEd38ZA11RGeNY8qRzt/SQCV5tlGhIXCqwIIM0IEhi7SgUj149goi0LLLGIWeRWYrZcxp6rn4L6rV6M2Cru2y3Eme/EO8PsCV4N5tZqO3fU23jnhJFyid1X9v0n+7uaY0QSaSwBoVTE75AFwifh2TS4iHVB94oNJ4ezhLmV7j4KGEi3MiJANfKX+g5PCuGQ58FyUoJL+b0u/3yGIa/EXDrwDflx4PaeBS77fOrC7ykljTXE2kH39wZlmOCIl0Mk3rfDOCT2Qu+g3x8mf3nDzvbAMHaavGfRrqkvLOXby/jiJ9HOX98pLfHEGlQQ9JsF1GDoAmY3EHb7n9sp3n7Wgh/OxDw2amsk+GeMz0OFjqh5eIEowNJqPTo5pxXivaxPCWXkUqq1dPG4+obv27718olxGxyTCKaxzVoElT6RMhZKK4kFQMOyWuPP4mEDmw9J7ZTopBHFwxtBts4noa1A7LOBj+Dk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
