travis:
  secure:
    BINSTAR_TOKEN: G2bpigXq1lNWKHRFfedT8mlAUaWTAY+nD7R9cHFiiFmoW/0cYi0ZcJWTr2ENaLNiQNeXrc11EHvORn/TQJhUTAQcPQUkf39KLoAlXEZ74zLBQCBnM6wcHCFshPX6at/xctha3gjFCD2bMnp6brFPRf8FmbDkfvAKbAv8VqRhHDkSs1Uw1gALDT8C4E3sivK29Zd7mDkKFEcrCAiDIVzWdnv2eSrYpPIx22PtiyXmssoSdxNqPFx5MiBClRAakdObwKQCaw62Fa74/6BQ9yjXxoq2bHPRTWwALZ1HlUmnvCrH3sUeLVng3FQkBwzBoRwH8a3PkItdKb3FaWcgMyQGkSD/cs5Uw5hqKgMDyRV20K3s8lVHFr3NMqqwJhZcAlBvu4sv0zZubgpc8s16Rb9hkji8ijb5DJJfM3DrGgMlbBvBgBVTFdZIHZ9ksFVJjRAIwj8aKnCz2uAASaS3EZd3NFpN20lb4bhyK02UeOSUV2SXReXTdUMhTEPlkYhiL7VkrHqAtmIX2beKtiacF9UPIU00OQ3GKnpnNwuGh4QNIcfJ95vpwlDQi93v3DiP0CMy/EykXyzsAlmzLL7LAAbb5wuHfOQTiM1mw0NLMMaXYpa7mgRAmYGVyxq1Xk6P168p3dmPY++F4Psp96F7N6/0hcTUaB+B7jk7NkShKnO2MoA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
